---
title: "MassWateR: Improving quality control, analysis, and sharing of water quality data"
date: "`r Sys.Date()`"
abstract: >
  An abstract of less than 150 words.
draft: true
author:  
  # see ?rjournal_article for more information
  - name: Marcus W. Beck
    affiliation: Tampa Bay Estuary Program
    address:
    - 263 13th Ave S
    - St. Petersburg, Florida, USA 33701
    url: https://tbep.org
    orcid: 0000-0002-4996-0059
    email:  mbeck@tbep.org
  - name: Benjamen Wetherill
    url: https://www.acasak.com/
    email: bwetherill@acasak.co
    affiliation: ACASAK Consulting
    address:
    - Boston, Massachusetts, USA
    orcid: 0000-0002-0912-0225
  - name: Jillian Carr
    url: https://www.mass.gov/orgs/massachusetts-bays-national-estuary-partnership
    email: Jillian.Carr@umb.edu
    affiliation: Massachusetts Bays National Estuary Partnership
    address:
    - University of Massachusetts Boston, 100 Morrissey Blvd
    - Boston, Massachusetts, USA 02125
  - name: Pamela DiBona
    url: https://www.mass.gov/orgs/massachusetts-bays-national-estuary-partnership
    email: pamela.dibona@state.ma.us
    affiliation: Massachusetts Bays National Estuary Partnership
    address:
    - University of Massachusetts Boston, 100 Morrissey Blvd
    - Boston, Massachusetts, USA 02125
type: package
output: 
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
bibliography: RJreferences.bib

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(MassWateR)
```

# Introduction

Water quality measurements provide the foundation of environmental monitoring programs designed to protect or restore aquatic resources [@Schiff16]. In the United States, most water quality monitoring programs are broadly guided by the federal Clean Water Act with the singular goal of restoring and maintaining the chemical, physical, and biological integrity of the nation's surface waters.  Similarly, the Water Framework Directive adopted in 2000 provides a framework for the protection of aquatic resources in member states of the European Union.  Numeric standards that define critical thresholds for protecting recreational, aquatic life, industrial, navigation and consumptive uses of the resource are often established, that, if exceeded based on water quality measurements, require additional regulatory action to ensure compliance. These standards are often developed at the state-level either using existing databases from long-term monitoring datasets, or data collected *ad hoc* from a variety of sources, where the former is atypical for most surface water bodies.  Many state or regional institutions that assess water quality rely on decentralized data sources, often combining datasets from local watershed groups or participatory science programs rather than a single database that contains adequate coverage for areas of interest. Use of these monitoring data in a regulatory context is not possible unless standard operating procedures are adopted and the data fulfill quality control requirements.   

Monitoring data of sufficient quantity and quality are critical to ensure precise and accurate representation of environmental conditions.  A significant bottleneck in the use of monitoring data for environmental assessment of surface waters is the ability to clearly and efficiently indicate that the data fulfill applicable quality control (QC) criteria for inclusion in a consolidated database. Common QC checks for *in situ* field measurements or concentrations measured in the laboratory may include 1) comparison of the precision between replicate samples (duplicates), 2) comparison of a sample to a known concentration (spikes or instrument checks), and 3) precision of the measurement from an empty or blank sample (blanks).  An adequate number of QC samples must also be included in the dataset as a measure of "completeness".  These checks are often compiled in a single report for review by appropriate regulatory agencies.  For example, precision of duplicate samples for a given parameter must not vary 5% and at least 10% of the data should be dedicated to these checks as a measure of completeness.   For local monitoring groups that lack the resources to develop robust and repeatable workflows, QC reports are often prepared manually before submitting the data for review  This process is time-consuming and prone to errors, often limiting the amount of useful information that is submitted to formal databases.  

The R statistical programming language offers a valuable software platform for developing tools to improve the QC of water quality data.  The use of R with document generation systems offered through packages like \CRANpkg{knitr} [@Xie15] and \CRANpkg{rmarkdown} [@Allaire23] can be leveraged to generate QC reports that follow a standard format for review by regulatory agencies.  These tools can also be used to format water quality data for submission to state or national water quality databases, such as the Water Quality Exchange (WQX) database maintained by the US Environmental Protection Agency.  This database is the largest source of monitoring data in the United States that includes information on hydrologic conditions and chemical, physical, and biological measurements from surface waters.  Moreover, many environmental resource managers have the need to analysis status and trends in monitoring data and R packages such as \CRANpkg{ggplot2} [@Wickham16] offer useful approaches to visualize numerous water quality records in a single graph. Integrating this functionality into a single package is expected to have wide ranging utility for anyone collecting surface water data and is likely to improve the quality and insights obtained from these data.  

This paper describes the MassWateR package developed to improve how environmental professionals perform quality control, analysis, and sharing of monitoring data for surface waters.  The regional focus of the package is for monitoring data collected in Massachusetts, USA, with QC reports submitted to the Massachusetts Department of Environmental Protection and data submitted to the national WQX database.  Although the initial conception of MassWateR was meant to address regional needs in Massachusetts, there is nothing specific in the package that prevents its use outside of the state as the QC checks and analyses follow routine methods for data collected at locations elsewhere.  As such, this paper is written with emphasis on how the tools are broadly applicable to anyone interested in improving efficiency and reproducibility of QC checks, in addition to analysis of water quality data and submission to WQX as the largest source of water monitoring data in the US.  

# Background

To our knowledge, there are no existing R packages on CRAN that can be used to facilitate QC of water quality data.  However, there are several that can be used to retrieve and analysis data from existing sources.  The \CRANpkg{dataRetrieval} package [@DeCicco22] in particular has been used widely to retrieve data from the USEPA Water Quality Portal (WQP), which is the counterpart of the WQX system for accessing data submitted using the latter.  

Existing workflows or packages

Good tools for data extraction - dataRetrieval, NADA package, https://cran.r-project.org/web/views/Hydrology.html

Building the community of practice...

# Requirements for using MassWateR

Make a case for a unified format, cannot cater to all, input checks are meant assist in this effort

# Read

# Quality Control

# Analysis

# Data submission

# Building a community and future work

MassWater in other locations, expansion elsewhere

Inclusion of historical data

Inclusion for continuous monitoring data, consider outlier anlaysis, drift, biofouling, etc.

# Summary

# Acknowledgments