# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit paper.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(flextable)
library(dplyr)
library(here)

flextable::set_flextable_defaults(font.size = 7, padding = 0)

load(file = here('tabs/filerequirements.RData'))


## ----workflow, fig.cap = 'Workflow demonstrating how a user could engage with the \\CRANpkg{MassWateR} package. WQX: Water Quality Exchange; QC: Quality Control.', fig.alt='Workflow diagram showing four ways to engage with MassWateR', out.width='100%'----
knitr::include_graphics('figs/workflow.png')


## ----filreq-------------------------------------------------------------------
filerequirements %>% fontsize(part = 'all', size = 9)


## ----importflow, fig.cap = 'Pseudocode demonstrating the iterative process of importing a required data file for \\CRANpkg{MassWateR}.  All read functions import an Excel file from the user-specified path (e.g., `respth`) and the imported file is then passed to a check function.  The function exits if an error is encountered, allowing the user to manually fix the identified error and then import again.  After all checks are passed, a formatting function is applied to correct minor issues (e.g., standardize date format as YYYY-MM-DD) and the final data object is returned (e.g., `resdat`).', fig.alt='Diagram showing pseudocode for importing and fixing a data file with MassWateR', out.width='100%'----
knitr::include_graphics('figs/importflow.png')


## ---- echo = T, eval = T, message = F-----------------------------------------
library(MassWateR)

# import results data
respth <- system.file("extdata/ExampleResults.xlsx", package = "MassWateR")
resdat <- readMWRresults(respth)


## ---- eval = F, echo = T------------------------------------------------------
#> chk <- resdat
#> chk[4, 2] <- "Sample"
#> chk[135, 2] <- "Field"
#> checkMWRresults(chk)


## ---- echo = T, eval = F------------------------------------------------------
#> apply(readxl::read_excel('path/to/results.xlsx'), 2, unique)


## ---- results = 'hide', echo = T----------------------------------------------
# import results data
respth <- system.file("extdata/ExampleResults.xlsx", package = "MassWateR")
resdat <- readMWRresults(respth)

# import accuracy data
accpth <- system.file("extdata/ExampleDQOAccuracy.xlsx", package = "MassWateR")
accdat <- readMWRacc(accpth)

# import frequency and completeness data
frecompth <- system.file("extdata/ExampleDQOFrequencyCompleteness.xlsx", package = "MassWateR")
frecomdat <- readMWRfrecom(frecompth)

# import site data
sitpth <- system.file("extdata/ExampleSites.xlsx", package = "MassWateR")
sitdat <- readMWRsites(sitpth)

# import WQX metadata
wqxpth <- system.file("extdata/ExampleWQX.xlsx", package = "MassWateR")
wqxdat <- readMWRwqx(wqxpth)

# a list of input data frames
fsetls <- list(res = resdat, acc = accdat, frecom = frecomdat, sit = sitdat, wqx = wqxdat)


## ---- fig.height = 4, fig.width = 8, echo = T, out.width = '95%', fig.align = 'center'----
anlzMWRoutlier(fset = fsetls, param = "DO", group = "month")


## ---- echo = T----------------------------------------------------------------
anlzMWRoutlier(fset = fsetls, param = "DO", group = "month", 
  outliers = TRUE)


## ---- echo = T, eval = F------------------------------------------------------
#> # create word output
#> anlzMWRoutlierall(fset = fsetls, group = 'month', format = 'word',
#>   output_dir = getwd())
#> 
#> # create png output
#> anlzMWRoutlierall(fset = fsetls, group = 'month', format = 'png',
#>   output_dir = getwd())


## ---- echo = T, eval = F------------------------------------------------------
#> qcMWRreview(fset = fsetls, output_dir = getwd())


## ----qcex, fig.cap = "The first two of sixteen pages of the quality control report created by `qcMWRreview()` that evaluates the results data relative to data quality objectives.  The first page shows the data quality objectives for accuracy, frequency, and completeness.  The second page shows QC results for frequency and completeness.  Parameters shown in red or marked as 'MISS' failed the data quality objectives.  Users can edit the Word file as needed, e.g., entering the organization name or adding notes.", fig.alt = "A Word document showing the first two pages of the quality control report.", out.width = '50%', fig.show='hold'----
knitr::include_graphics('figs/qcreview1.png')
knitr::include_graphics('figs/qcreview2.png')


## ---- echo = T, eval = F------------------------------------------------------
#> tabMWRacc(fset = fsetls, type = "summary")

## ---- echo = F, eval = T------------------------------------------------------
resin <- resdat[resdat$`Characteristic Name` %in% c('Ammonia', 'TP'), ]
tabMWRacc(res = resin, acc = accdat, frecom = frecomdat, type = "summary")


## ---- echo = T----------------------------------------------------------------
tabMWRacc(fset = fsetls, type = "percent")


## ---- echo = T, eval = F------------------------------------------------------
#> tabMWRacc(fset = fsetls, type = "individual", accchk = "Field Blanks")

## ---- echo = F, eval = T------------------------------------------------------
resin <- resdat[resdat$`Characteristic Name` %in% c('TP', 'Ammonia') ,]
tabMWRacc(res = resin, acc = accdat, frecom = frecomdat, type = "individual", accchk = "Field Blanks", warn = F, caption = F)


## ----fig.height = 4, fig.width = 8, echo = T, out.width = '95%', fig.align = 'center'----
anlzMWRseason(fset = fsetls, param = "DO", thresh = "fresh", 
  group = "month", type = "jitterbox")


## ----fig.height = 4, fig.width = 8, echo = T, out.width = '95%', fig.align = 'center'----
anlzMWRdate(fset = fsetls, param = 'DO', group = 'locgroup', 
  thresh = 'fresh')


## ----fig.height = 4, fig.width = 8, echo = T,  out.width = '95%', fig.align = 'center'----
anlzMWRsite(fset = fsetls, param = "DO", thresh = "fresh", type = "box", 
  site = c("ABT-026", "ABT-062", "ABT-077", "ABT-144", "ABT-237", "ABT-301"),
  resultatt = c('DRY', 'WET'), byresultatt = TRUE)


## ----fig.height = 5, fig.width = 5, echo = T, out.width = '95%', fig.align = 'center'----
anlzMWRmap(fset = fsetls, param = "DO", addwater = "medium")


## ---- echo = T, eval = F------------------------------------------------------
#> tabMWRwqx(fset = fsetls, output_dir = getwd())
#> #> Excel workbook created successfully! File located at /tmp/RtmpBrk9nw/wqxtab.xlsx

